### ISSUE TITLE
Slightly confusing that memory names refer to addresses (even though they're typed)

### ISSUE THREAD

**Issue by binji** [ncbray/wassembler#1]
memory foo i32;
...
printI32(foo);  // prints 8 (the address of foo)
printI32(loadI32(foo));  // prints 0 (the value of foo)

This makes sense, but is not what the code looks like it is doing.

**Comment by ncbray** [comment]
I changed the syntax to "memory foo 4 align 4;".  No types, explicit alignment, less misleading, but still ugly.
